### ISSUE TITLE
SSL Certs

### ISSUE THREAD

**Issue by PixiBixi** [xataz/docker-jackett#1]
Hello buddy !

Un petit problème sur ton jackett facilement corrigeable

Les SSL ne sont pas à jour de base ce qui pose des pbs avec A*N par exemple.

update-ca-certificates ne marche pas pour info.

Il faut que tu wget https://curl.haxx.se/ca/cacert.pem puis cert-sync cacert.pem

Testé et approuvé.

BXT

PS: La log stack http://i.imgur.com/muclVHa.png

**Comment by xataz** [comment]
Tu as possibilité de retester, j'ai juste mis à jour alpine (musl), qui pose souvent problème avec les ca-certificates.

**Comment by PixiBixi** [comment]
Je vais voir pour retester ! ;)

**Comment by PixiBixi** [comment]
http://i.imgur.com/g8ue9U1.png Toujours pareil chef !
